export type CanonicalModuleCatalogEntry = {
  id: string;
  name: string;
  rarity: string;
  category: string;
  families: string;
  primaryPower: string;
  secondaryPower: string;
  condition: string;
  stackingGroup: string;
  stageGate: string;
  guaranteedAcquisition: string;
  minimumHunt: string;
  eventSource: string;
  earnedPackSource: string;
  cashPackEligible: boolean;
  craftParts: string;
  craftCost: number;
  craftTimeMin: number;
  craftTime: string;
  dismantleParts: number;
  role: string;
  directPerformance: boolean;
  directPlot: boolean;
  notes: string;
};

export const CANONICAL_MODULE_CATALOG: readonly CanonicalModuleCatalogEntry[] = [
  {
    "id": "mod_customer_signage",
    "name": "Customer Signage",
    "rarity": "Common",
    "category": "Customer",
    "families": "Cash Services, Banking, Lending, Brokerage, Insurance, Advisory, Wealth",
    "primaryPower": "+4% customer acquisition",
    "secondaryPower": "",
    "condition": "",
    "stackingGroup": "customer",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Earnings Season",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "Basic acquisition",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_queue_optimizer",
    "name": "Queue Optimizer",
    "rarity": "Common",
    "category": "Operations",
    "families": "All",
    "primaryPower": "+5% capacity",
    "secondaryPower": "",
    "condition": "",
    "stackingGroup": "operations",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Regulatory Approval",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "Capacity",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_service_playbook",
    "name": "Service Playbook",
    "rarity": "Common",
    "category": "Service",
    "families": "All customer-facing",
    "primaryPower": "+3 Service Quality",
    "secondaryPower": "",
    "condition": "",
    "stackingGroup": "service",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Earnings Season",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "Service",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_risk_checklist",
    "name": "Risk Checklist",
    "rarity": "Common",
    "category": "Risk",
    "families": "All",
    "primaryPower": "-3 Operational Risk",
    "secondaryPower": "",
    "condition": "",
    "stackingGroup": "risk",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Regulatory Approval",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "Risk control",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_reserve_discipline",
    "name": "Reserve Discipline",
    "rarity": "Common",
    "category": "Liquidity",
    "families": "Banking, Treasury, FX, Exchange, Market Making",
    "primaryPower": "-4 Liquidity Risk",
    "secondaryPower": "-2% activity efficiency",
    "condition": "",
    "stackingGroup": "liquidity",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Liquidity Crunch",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "Defensive liquidity",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_local_promotions",
    "name": "Local Promotions",
    "rarity": "Common",
    "category": "Customer",
    "families": "Cash Services, Banking, Lending, Insurance",
    "primaryPower": "+5% General Consumer acquisition",
    "secondaryPower": "",
    "condition": "",
    "stackingGroup": "customer",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Earnings Season",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "Consumer growth",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_fast_onboarding",
    "name": "Fast Onboarding",
    "rarity": "Common",
    "category": "Operations",
    "families": "Banking, Brokerage, Lending, Fintech, Advisory",
    "primaryPower": "+4% customer acquisition",
    "secondaryPower": "+2% capacity",
    "condition": "",
    "stackingGroup": "operations",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Regulatory Approval",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "Onboarding",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_basic_crm",
    "name": "Basic CRM",
    "rarity": "Common",
    "category": "Service",
    "families": "Banking, Advisory, Wealth, Insurance",
    "primaryPower": "+4% retention",
    "secondaryPower": "",
    "condition": "",
    "stackingGroup": "service",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Earnings Season",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "Retention",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_capacity_planner",
    "name": "Capacity Planner",
    "rarity": "Common",
    "category": "Operations",
    "families": "All",
    "primaryPower": "+4% capacity",
    "secondaryPower": "-1 Service Quality",
    "condition": "",
    "stackingGroup": "operations",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Generic Module reward pool",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "Capacity",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_shift_scheduler",
    "name": "Shift Scheduler",
    "rarity": "Common",
    "category": "Operations",
    "families": "All",
    "primaryPower": "+3% activity efficiency",
    "secondaryPower": "",
    "condition": "",
    "stackingGroup": "operations",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Generic Module reward pool",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "Operations",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_cost_ledger",
    "name": "Cost Ledger",
    "rarity": "Common",
    "category": "Operations",
    "families": "All",
    "primaryPower": "-3% operating cost",
    "secondaryPower": "",
    "condition": "",
    "stackingGroup": "operations",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Rate Hike",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "Cost control",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_backup_procedures",
    "name": "Backup Procedures",
    "rarity": "Common",
    "category": "Risk",
    "families": "Fintech, Data, Trading, Exchange, Research",
    "primaryPower": "-3 Operational Risk",
    "secondaryPower": "+1 Service Quality",
    "condition": "",
    "stackingGroup": "risk",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Volatility Spike",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "Reliability",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_cash_handling_protocol",
    "name": "Cash Handling Protocol",
    "rarity": "Common",
    "category": "Liquidity",
    "families": "Cash Services, Banking, Treasury",
    "primaryPower": "-3 Liquidity Risk",
    "secondaryPower": "+2 Service Quality",
    "condition": "",
    "stackingGroup": "liquidity",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Bank Run",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "Cash discipline",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_simple_credit_checklist",
    "name": "Simple Credit Checklist",
    "rarity": "Common",
    "category": "Credit",
    "families": "Lending, Banking",
    "primaryPower": "-3 Credit Risk",
    "secondaryPower": "-2% activity efficiency",
    "condition": "",
    "stackingGroup": "credit",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Credit Boom",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "Credit control",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_order_book_basics",
    "name": "Order Book Basics",
    "rarity": "Common",
    "category": "Market",
    "families": "Trading, Brokerage, Exchange, Market Making",
    "primaryPower": "+4% activity efficiency",
    "secondaryPower": "+2 Market Risk",
    "condition": "",
    "stackingGroup": "market",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Bull Market",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "Trading throughput",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_research_notes",
    "name": "Research Notes",
    "rarity": "Common",
    "category": "Research",
    "families": "Research, Data, Brokerage, Asset Management, Advisory",
    "primaryPower": "+3% activity efficiency",
    "secondaryPower": "+1 Service Quality",
    "condition": "",
    "stackingGroup": "research",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Tech Rally",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "Research support",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_client_suitability_form",
    "name": "Client Suitability Form",
    "rarity": "Common",
    "category": "Risk",
    "families": "Brokerage, Advisory, Wealth",
    "primaryPower": "-3 Reputation Risk",
    "secondaryPower": "-1% acquisition",
    "condition": "",
    "stackingGroup": "risk",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Regulatory Approval",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "Suitability",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_claims_triage",
    "name": "Claims Triage",
    "rarity": "Common",
    "category": "Service",
    "families": "Insurance",
    "primaryPower": "+4% retention",
    "secondaryPower": "+2 Service Quality",
    "condition": "",
    "stackingGroup": "service",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Generic Module reward pool",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "Claims service",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_savings_drive",
    "name": "Savings Drive",
    "rarity": "Common",
    "category": "Customer",
    "families": "Banking",
    "primaryPower": "+5% General Consumer acquisition",
    "secondaryPower": "-1% activity efficiency",
    "condition": "",
    "stackingGroup": "customer",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Rate Cut",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "Deposit growth",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_fx_rate_board",
    "name": "FX Rate Board",
    "rarity": "Common",
    "category": "Market",
    "families": "FX",
    "primaryPower": "+4% activity efficiency",
    "secondaryPower": "+1 Market Risk",
    "condition": "",
    "stackingGroup": "market",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Volatility Spike",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "FX activity",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_portfolio_watchlist",
    "name": "Portfolio Watchlist",
    "rarity": "Common",
    "category": "Research",
    "families": "Asset Management, Wealth, Brokerage",
    "primaryPower": "+3% activity efficiency",
    "secondaryPower": "-2 Concentration Risk",
    "condition": "",
    "stackingGroup": "research",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Dividend Week",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "Portfolio support",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_basic_security_controls",
    "name": "Basic Security Controls",
    "rarity": "Common",
    "category": "Risk",
    "families": "Fintech, Data, Exchange",
    "primaryPower": "-4 Operational Risk",
    "secondaryPower": "-1% activity efficiency",
    "condition": "",
    "stackingGroup": "risk",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Regulatory Approval",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "Security",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_call_queue_script",
    "name": "Call Queue Script",
    "rarity": "Common",
    "category": "Service",
    "families": "Banking, Insurance, Advisory, Wealth",
    "primaryPower": "+3 Service Quality",
    "secondaryPower": "+2% retention",
    "condition": "",
    "stackingGroup": "service",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Earnings Season",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "Customer care",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_deposit_reminder",
    "name": "Deposit Reminder",
    "rarity": "Common",
    "category": "Customer",
    "families": "Banking",
    "primaryPower": "+4% retention",
    "secondaryPower": "",
    "condition": "",
    "stackingGroup": "customer",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Rate Hike",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "Deposit retention",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_merchant_outreach",
    "name": "Merchant Outreach",
    "rarity": "Common",
    "category": "Customer",
    "families": "Cash Services, Banking",
    "primaryPower": "+5% Small Business acquisition",
    "secondaryPower": "",
    "condition": "",
    "stackingGroup": "customer",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "M&A Boom",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "SME growth",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_trade_confirmation",
    "name": "Trade Confirmation",
    "rarity": "Common",
    "category": "Operations",
    "families": "Trading, Brokerage, Exchange",
    "primaryPower": "-2 Operational Risk",
    "secondaryPower": "+3% capacity",
    "condition": "",
    "stackingGroup": "operations",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Volatility Spike",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "Trade ops",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_vault_inventory_log",
    "name": "Vault Inventory Log",
    "rarity": "Common",
    "category": "Liquidity",
    "families": "Treasury, Cash Services",
    "primaryPower": "-3 Liquidity Risk",
    "secondaryPower": "-2 Operational Risk",
    "condition": "",
    "stackingGroup": "liquidity",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Liquidity Crunch",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "Vault control",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_data_quality_checklist",
    "name": "Data Quality Checklist",
    "rarity": "Common",
    "category": "Research",
    "families": "Research, Data, Fintech",
    "primaryPower": "+2 Service Quality",
    "secondaryPower": "-3 Operational Risk",
    "condition": "",
    "stackingGroup": "research",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Tech Rally",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "Data quality",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_kyc_desk_guide",
    "name": "KYC Desk Guide",
    "rarity": "Common",
    "category": "Risk",
    "families": "Banking, Brokerage, Advisory, Wealth, Private Banking",
    "primaryPower": "-3 Reputation Risk",
    "secondaryPower": "+1 Service Quality",
    "condition": "",
    "stackingGroup": "risk",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Regulatory Approval",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "Compliance",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_appointment_book",
    "name": "Appointment Book",
    "rarity": "Common",
    "category": "Service",
    "families": "Advisory, Wealth, Private Banking",
    "primaryPower": "+4% retention",
    "secondaryPower": "+2 Service Quality",
    "condition": "",
    "stackingGroup": "service",
    "stageGate": "Humble",
    "guaranteedAcquisition": "Mastery I — choose from compatible family pool",
    "minimumHunt": "Easy",
    "eventSource": "Earnings Season",
    "earnedPackSource": "Basic Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Common Parts",
    "craftCost": 25,
    "craftTimeMin": 0,
    "craftTime": "Instant",
    "dismantleParts": 5,
    "role": "Relationship service",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_lean_operations",
    "name": "Lean Operations",
    "rarity": "Uncommon",
    "category": "Operations",
    "families": "All",
    "primaryPower": "-6% operating cost",
    "secondaryPower": "-2 Service Quality",
    "condition": "",
    "stackingGroup": "operations",
    "stageGate": "Starter",
    "guaranteedAcquisition": "Mastery II — choose from compatible family pool",
    "minimumHunt": "Standard",
    "eventSource": "Rate Hike",
    "earnedPackSource": "Basic / Advanced Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Uncommon Parts",
    "craftCost": 60,
    "craftTimeMin": 15,
    "craftTime": "15 min",
    "dismantleParts": 12,
    "role": "Efficiency sidegrade",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_sme_relationship_desk",
    "name": "SME Relationship Desk",
    "rarity": "Uncommon",
    "category": "Customer",
    "families": "Banking, Lending, Advisory",
    "primaryPower": "+8% Small Business acquisition",
    "secondaryPower": "-3% General Consumer acquisition",
    "condition": "",
    "stackingGroup": "customer",
    "stageGate": "Starter",
    "guaranteedAcquisition": "Mastery II — choose from compatible family pool",
    "minimumHunt": "Standard",
    "eventSource": "M&A Boom",
    "earnedPackSource": "Basic / Advanced Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Uncommon Parts",
    "craftCost": 60,
    "craftTimeMin": 15,
    "craftTime": "15 min",
    "dismantleParts": 12,
    "role": "SME specialization",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_retail_investor_campaign",
    "name": "Retail Investor Campaign",
    "rarity": "Uncommon",
    "category": "Customer",
    "families": "Brokerage, Trading, Advisory",
    "primaryPower": "+8% Retail Investor acquisition",
    "secondaryPower": "+2 Reputation Risk if Service <60",
    "condition": "Service Quality >=60",
    "stackingGroup": "customer",
    "stageGate": "Starter",
    "guaranteedAcquisition": "Mastery II — choose from compatible family pool",
    "minimumHunt": "Standard",
    "eventSource": "Bull Market",
    "earnedPackSource": "Basic / Advanced Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Uncommon Parts",
    "craftCost": 60,
    "craftTimeMin": 15,
    "craftTime": "15 min",
    "dismantleParts": 12,
    "role": "Retail growth",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_claims_automation",
    "name": "Claims Automation",
    "rarity": "Uncommon",
    "category": "Service",
    "families": "Insurance",
    "primaryPower": "+5 Service Quality",
    "secondaryPower": "-3 Operational Risk",
    "condition": "",
    "stackingGroup": "service",
    "stageGate": "Starter",
    "guaranteedAcquisition": "Mastery II — choose from compatible family pool",
    "minimumHunt": "Standard",
    "eventSource": "Regulatory Approval",
    "earnedPackSource": "Basic / Advanced Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Uncommon Parts",
    "craftCost": 60,
    "craftTimeMin": 15,
    "craftTime": "15 min",
    "dismantleParts": 12,
    "role": "Insurance automation",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_smart_order_routing",
    "name": "Smart Order Routing",
    "rarity": "Uncommon",
    "category": "Market",
    "families": "Trading, Brokerage, Exchange, Market Making",
    "primaryPower": "+7% capacity",
    "secondaryPower": "+2% activity efficiency",
    "condition": "",
    "stackingGroup": "market",
    "stageGate": "Starter",
    "guaranteedAcquisition": "Mastery II — choose from compatible family pool",
    "minimumHunt": "Standard",
    "eventSource": "Volatility Spike",
    "earnedPackSource": "Basic / Advanced Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Uncommon Parts",
    "craftCost": 60,
    "craftTimeMin": 15,
    "craftTime": "15 min",
    "dismantleParts": 12,
    "role": "Execution",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_conservative_underwriting",
    "name": "Conservative Underwriting",
    "rarity": "Uncommon",
    "category": "Credit",
    "families": "Lending, Banking",
    "primaryPower": "-6 Credit Risk",
    "secondaryPower": "-5% activity efficiency",
    "condition": "",
    "stackingGroup": "credit",
    "stageGate": "Starter",
    "guaranteedAcquisition": "Mastery II — choose from compatible family pool",
    "minimumHunt": "Standard",
    "eventSource": "Credit Boom",
    "earnedPackSource": "Basic / Advanced Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Uncommon Parts",
    "craftCost": 60,
    "craftTimeMin": 15,
    "craftTime": "15 min",
    "dismantleParts": 12,
    "role": "Defensive lending",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_concierge_desk",
    "name": "Concierge Desk",
    "rarity": "Uncommon",
    "category": "Wealth",
    "families": "Wealth, Private Banking, Advisory",
    "primaryPower": "+8% HNW acquisition",
    "secondaryPower": "-4% General Consumer acquisition",
    "condition": "",
    "stackingGroup": "wealth",
    "stageGate": "Starter",
    "guaranteedAcquisition": "Mastery II — choose from compatible family pool",
    "minimumHunt": "Standard",
    "eventSource": "Dividend Week",
    "earnedPackSource": "Basic / Advanced Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Uncommon Parts",
    "craftCost": 60,
    "craftTimeMin": 15,
    "craftTime": "15 min",
    "dismantleParts": 12,
    "role": "HNW acquisition",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_liquidity_dashboard",
    "name": "Liquidity Dashboard",
    "rarity": "Uncommon",
    "category": "Liquidity",
    "families": "Banking, Treasury, FX, Market Making, Exchange",
    "primaryPower": "-6 Liquidity Risk",
    "secondaryPower": "-2% operating cost efficiency",
    "condition": "",
    "stackingGroup": "liquidity",
    "stageGate": "Starter",
    "guaranteedAcquisition": "Mastery II — choose from compatible family pool",
    "minimumHunt": "Standard",
    "eventSource": "Liquidity Crunch",
    "earnedPackSource": "Basic / Advanced Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Uncommon Parts",
    "craftCost": 60,
    "craftTimeMin": 15,
    "craftTime": "15 min",
    "dismantleParts": 12,
    "role": "Liquidity control",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_client_segmentation",
    "name": "Client Segmentation",
    "rarity": "Uncommon",
    "category": "Customer",
    "families": "Banking, Brokerage, Insurance, Advisory",
    "primaryPower": "+6% acquisition",
    "secondaryPower": "+4% retention",
    "condition": "Targeting overhead: -2% capacity",
    "stackingGroup": "customer",
    "stageGate": "Starter",
    "guaranteedAcquisition": "Mastery II — choose from compatible family pool",
    "minimumHunt": "Standard",
    "eventSource": "Earnings Season",
    "earnedPackSource": "Basic / Advanced Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Uncommon Parts",
    "craftCost": 60,
    "craftTimeMin": 15,
    "craftTime": "15 min",
    "dismantleParts": 12,
    "role": "Segmentation",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_fee_optimization",
    "name": "Fee Optimization",
    "rarity": "Uncommon",
    "category": "Operations",
    "families": "All",
    "primaryPower": "-7% operating cost",
    "secondaryPower": "-3% customer acquisition",
    "condition": "",
    "stackingGroup": "operations",
    "stageGate": "Starter",
    "guaranteedAcquisition": "Mastery II — choose from compatible family pool",
    "minimumHunt": "Standard",
    "eventSource": "Rate Hike",
    "earnedPackSource": "Basic / Advanced Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Uncommon Parts",
    "craftCost": 60,
    "craftTimeMin": 15,
    "craftTime": "15 min",
    "dismantleParts": 12,
    "role": "Cost vs growth",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_branch_workflow",
    "name": "Branch Workflow",
    "rarity": "Uncommon",
    "category": "Operations",
    "families": "Banking, Lending, Insurance",
    "primaryPower": "+7% capacity",
    "secondaryPower": "+2 Service Quality",
    "condition": "",
    "stackingGroup": "operations",
    "stageGate": "Starter",
    "guaranteedAcquisition": "Mastery II — choose from compatible family pool",
    "minimumHunt": "Standard",
    "eventSource": "Generic Module reward pool",
    "earnedPackSource": "Basic / Advanced Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Uncommon Parts",
    "craftCost": 60,
    "craftTimeMin": 15,
    "craftTime": "15 min",
    "dismantleParts": 12,
    "role": "Branch efficiency",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_cross_sell_playbook",
    "name": "Cross-Sell Playbook",
    "rarity": "Uncommon",
    "category": "Customer",
    "families": "Banking, Wealth, Advisory, Insurance",
    "primaryPower": "+6% retention",
    "secondaryPower": "+5% activity efficiency",
    "condition": "+2 Reputation Risk if Service <65",
    "stackingGroup": "customer",
    "stageGate": "Starter",
    "guaranteedAcquisition": "Mastery II — choose from compatible family pool",
    "minimumHunt": "Standard",
    "eventSource": "Earnings Season",
    "earnedPackSource": "Basic / Advanced Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Uncommon Parts",
    "craftCost": 60,
    "craftTimeMin": 15,
    "craftTime": "15 min",
    "dismantleParts": 12,
    "role": "Cross-sell",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_research_terminal",
    "name": "Research Terminal",
    "rarity": "Uncommon",
    "category": "Research",
    "families": "Research, Brokerage, Asset Management, Advisory",
    "primaryPower": "+6% activity efficiency",
    "secondaryPower": "+3 Service Quality",
    "condition": "",
    "stackingGroup": "research",
    "stageGate": "Starter",
    "guaranteedAcquisition": "Mastery II — choose from compatible family pool",
    "minimumHunt": "Standard",
    "eventSource": "Tech Rally",
    "earnedPackSource": "Basic / Advanced Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Uncommon Parts",
    "craftCost": 60,
    "craftTimeMin": 15,
    "craftTime": "15 min",
    "dismantleParts": 12,
    "role": "Research",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_risk_alerting",
    "name": "Risk Alerting",
    "rarity": "Uncommon",
    "category": "Risk",
    "families": "All",
    "primaryPower": "-5 Operational Risk",
    "secondaryPower": "-3 Market Risk",
    "condition": "Composite Risk <=70",
    "stackingGroup": "risk",
    "stageGate": "Starter",
    "guaranteedAcquisition": "Mastery II — choose from compatible family pool",
    "minimumHunt": "Standard",
    "eventSource": "Market Correction",
    "earnedPackSource": "Basic / Advanced Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Uncommon Parts",
    "craftCost": 60,
    "craftTimeMin": 15,
    "craftTime": "15 min",
    "dismantleParts": 12,
    "role": "Risk monitoring",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_treasury_sweep",
    "name": "Treasury Sweep",
    "rarity": "Uncommon",
    "category": "Liquidity",
    "families": "Treasury, Banking",
    "primaryPower": "-6 Liquidity Risk",
    "secondaryPower": "+4% capacity",
    "condition": "Reserve Ratio >=10%",
    "stackingGroup": "liquidity",
    "stageGate": "Starter",
    "guaranteedAcquisition": "Mastery II — choose from compatible family pool",
    "minimumHunt": "Standard",
    "eventSource": "Liquidity Crunch",
    "earnedPackSource": "Basic / Advanced Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Uncommon Parts",
    "craftCost": 60,
    "craftTimeMin": 15,
    "craftTime": "15 min",
    "dismantleParts": 12,
    "role": "Treasury efficiency",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_fx_netting",
    "name": "FX Netting",
    "rarity": "Uncommon",
    "category": "Market",
    "families": "FX, Treasury",
    "primaryPower": "-5 Liquidity Risk",
    "secondaryPower": "+5% activity efficiency; +2 Market Risk",
    "condition": "",
    "stackingGroup": "market",
    "stageGate": "Starter",
    "guaranteedAcquisition": "Mastery II — choose from compatible family pool",
    "minimumHunt": "Standard",
    "eventSource": "Volatility Spike",
    "earnedPackSource": "Basic / Advanced Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Uncommon Parts",
    "craftCost": 60,
    "craftTimeMin": 15,
    "craftTime": "15 min",
    "dismantleParts": 12,
    "role": "FX optimization",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_digital_onboarding",
    "name": "Digital Onboarding",
    "rarity": "Uncommon",
    "category": "Operations",
    "families": "Fintech, Banking, Brokerage, Wealth",
    "primaryPower": "+7% acquisition",
    "secondaryPower": "+4% capacity; +2 Operational Risk",
    "condition": "",
    "stackingGroup": "operations",
    "stageGate": "Starter",
    "guaranteedAcquisition": "Mastery II — choose from compatible family pool",
    "minimumHunt": "Standard",
    "eventSource": "Tech Rally",
    "earnedPackSource": "Basic / Advanced Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Uncommon Parts",
    "craftCost": 60,
    "craftTimeMin": 15,
    "craftTime": "15 min",
    "dismantleParts": 12,
    "role": "Digital growth",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_corporate_prospecting",
    "name": "Corporate Prospecting",
    "rarity": "Uncommon",
    "category": "Institutional",
    "families": "Investment Banking, Banking, Advisory",
    "primaryPower": "+8% Corporate Client acquisition",
    "secondaryPower": "-4% General Consumer acquisition",
    "condition": "",
    "stackingGroup": "institutional",
    "stageGate": "Starter",
    "guaranteedAcquisition": "Mastery II — choose from compatible family pool",
    "minimumHunt": "Standard",
    "eventSource": "M&A Boom",
    "earnedPackSource": "Basic / Advanced Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Uncommon Parts",
    "craftCost": 60,
    "craftTimeMin": 15,
    "craftTime": "15 min",
    "dismantleParts": 12,
    "role": "Corporate acquisition",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_portfolio_rebalancing",
    "name": "Portfolio Rebalancing",
    "rarity": "Uncommon",
    "category": "Risk",
    "families": "Asset Management, Wealth",
    "primaryPower": "-5 Concentration Risk",
    "secondaryPower": "+4% activity efficiency",
    "condition": "",
    "stackingGroup": "risk",
    "stageGate": "Starter",
    "guaranteedAcquisition": "Mastery II — choose from compatible family pool",
    "minimumHunt": "Standard",
    "eventSource": "Market Correction",
    "earnedPackSource": "Basic / Advanced Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Uncommon Parts",
    "craftCost": 60,
    "craftTimeMin": 15,
    "craftTime": "15 min",
    "dismantleParts": 12,
    "role": "Portfolio balance",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_fraud_screening",
    "name": "Fraud Screening",
    "rarity": "Uncommon",
    "category": "Risk",
    "families": "Banking, Fintech, Brokerage, Insurance",
    "primaryPower": "-6 Operational Risk",
    "secondaryPower": "-3% capacity",
    "condition": "",
    "stackingGroup": "risk",
    "stageGate": "Starter",
    "guaranteedAcquisition": "Mastery II — choose from compatible family pool",
    "minimumHunt": "Standard",
    "eventSource": "Regulatory Approval",
    "earnedPackSource": "Basic / Advanced Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Uncommon Parts",
    "craftCost": 60,
    "craftTimeMin": 15,
    "craftTime": "15 min",
    "dismantleParts": 12,
    "role": "Fraud prevention",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_uptime_monitoring",
    "name": "Uptime Monitoring",
    "rarity": "Uncommon",
    "category": "Operations",
    "families": "Fintech, Data, Exchange, Trading",
    "primaryPower": "+6% capacity",
    "secondaryPower": "-4 Operational Risk",
    "condition": "",
    "stackingGroup": "operations",
    "stageGate": "Starter",
    "guaranteedAcquisition": "Mastery II — choose from compatible family pool",
    "minimumHunt": "Standard",
    "eventSource": "Tech Rally",
    "earnedPackSource": "Basic / Advanced Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Uncommon Parts",
    "craftCost": 60,
    "craftTimeMin": 15,
    "craftTime": "15 min",
    "dismantleParts": 12,
    "role": "Reliability",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_data_enrichment",
    "name": "Data Enrichment",
    "rarity": "Uncommon",
    "category": "Research",
    "families": "Data, Research, Fintech, Brokerage",
    "primaryPower": "+5% activity efficiency",
    "secondaryPower": "+4 Service Quality",
    "condition": "",
    "stackingGroup": "research",
    "stageGate": "Starter",
    "guaranteedAcquisition": "Mastery II — choose from compatible family pool",
    "minimumHunt": "Standard",
    "eventSource": "Tech Rally",
    "earnedPackSource": "Basic / Advanced Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Uncommon Parts",
    "craftCost": 60,
    "craftTimeMin": 15,
    "craftTime": "15 min",
    "dismantleParts": 12,
    "role": "Data improvement",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_market_news_feed",
    "name": "Market News Feed",
    "rarity": "Uncommon",
    "category": "Research",
    "families": "Trading, Brokerage, Asset Management, Advisory",
    "primaryPower": "+6% activity efficiency",
    "secondaryPower": "+2 Market Risk",
    "condition": "",
    "stackingGroup": "research",
    "stageGate": "Starter",
    "guaranteedAcquisition": "Mastery II — choose from compatible family pool",
    "minimumHunt": "Standard",
    "eventSource": "Bull Market",
    "earnedPackSource": "Basic / Advanced Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Uncommon Parts",
    "craftCost": 60,
    "craftTimeMin": 15,
    "craftTime": "15 min",
    "dismantleParts": 12,
    "role": "Market intel",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_service_recovery_desk",
    "name": "Service Recovery Desk",
    "rarity": "Uncommon",
    "category": "Service",
    "families": "All customer-facing",
    "primaryPower": "+6% retention",
    "secondaryPower": "+4 Service Quality",
    "condition": "Utilization <=95%",
    "stackingGroup": "service",
    "stageGate": "Starter",
    "guaranteedAcquisition": "Mastery II — choose from compatible family pool",
    "minimumHunt": "Standard",
    "eventSource": "Bank Run",
    "earnedPackSource": "Basic / Advanced Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Uncommon Parts",
    "craftCost": 60,
    "craftTimeMin": 15,
    "craftTime": "15 min",
    "dismantleParts": 12,
    "role": "Retention",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_deposit_loyalty_program",
    "name": "Deposit Loyalty Program",
    "rarity": "Uncommon",
    "category": "Customer",
    "families": "Banking",
    "primaryPower": "+8% retention",
    "secondaryPower": "-3% acquisition",
    "condition": "",
    "stackingGroup": "customer",
    "stageGate": "Starter",
    "guaranteedAcquisition": "Mastery II — choose from compatible family pool",
    "minimumHunt": "Standard",
    "eventSource": "Rate Hike",
    "earnedPackSource": "Basic / Advanced Earned Pack",
    "cashPackEligible": true,
    "craftParts": "Uncommon Parts",
    "craftCost": 60,
    "craftTimeMin": 15,
    "craftTime": "15 min",
    "dismantleParts": 12,
    "role": "Deposit loyalty",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_reserve_buffer",
    "name": "Reserve Buffer",
    "rarity": "Rare",
    "category": "Liquidity",
    "families": "Banking, Treasury, Market Making",
    "primaryPower": "-8 Liquidity Risk",
    "secondaryPower": "-4% activity efficiency",
    "condition": "",
    "stackingGroup": "liquidity",
    "stageGate": "Growing",
    "guaranteedAcquisition": "Mastery III — choose from compatible family pool",
    "minimumHunt": "Hard",
    "eventSource": "Liquidity Crunch",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Rare Parts",
    "craftCost": 150,
    "craftTimeMin": 60,
    "craftTime": "1 hour",
    "dismantleParts": 30,
    "role": "Strong defense",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_growth_underwriting",
    "name": "Growth Underwriting",
    "rarity": "Rare",
    "category": "Credit",
    "families": "Lending, Banking",
    "primaryPower": "+12% activity efficiency",
    "secondaryPower": "+6 Credit Risk",
    "condition": "",
    "stackingGroup": "credit",
    "stageGate": "Growing",
    "guaranteedAcquisition": "Mastery III — choose from compatible family pool",
    "minimumHunt": "Hard",
    "eventSource": "Credit Boom",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Rare Parts",
    "craftCost": 150,
    "craftTimeMin": 60,
    "craftTime": "1 hour",
    "dismantleParts": 30,
    "role": "Aggressive lending",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_high_velocity_desk",
    "name": "High Velocity Desk",
    "rarity": "Rare",
    "category": "Market",
    "families": "Trading, Brokerage, Exchange",
    "primaryPower": "+12% activity efficiency",
    "secondaryPower": "+6 Market Risk",
    "condition": "",
    "stackingGroup": "market",
    "stageGate": "Growing",
    "guaranteedAcquisition": "Mastery III — choose from compatible family pool",
    "minimumHunt": "Hard",
    "eventSource": "Volatility Spike",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Rare Parts",
    "craftCost": 150,
    "craftTimeMin": 60,
    "craftTime": "1 hour",
    "dismantleParts": 30,
    "role": "Aggressive trading",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_circuit_breaker",
    "name": "Circuit Breaker",
    "rarity": "Rare",
    "category": "Risk",
    "families": "Trading, Exchange, Market Making",
    "primaryPower": "-8 Market Risk",
    "secondaryPower": "-6% activity efficiency",
    "condition": "",
    "stackingGroup": "risk",
    "stageGate": "Growing",
    "guaranteedAcquisition": "Mastery III — choose from compatible family pool",
    "minimumHunt": "Hard",
    "eventSource": "Market Correction",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Rare Parts",
    "craftCost": 150,
    "craftTimeMin": 60,
    "craftTime": "1 hour",
    "dismantleParts": 30,
    "role": "Defensive trading",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_premium_relationship_team",
    "name": "Premium Relationship Team",
    "rarity": "Rare",
    "category": "Wealth",
    "families": "Banking, Wealth, Private Banking",
    "primaryPower": "+10% HNW retention",
    "secondaryPower": "-5% General Consumer acquisition",
    "condition": "",
    "stackingGroup": "wealth",
    "stageGate": "Growing",
    "guaranteedAcquisition": "Mastery III — choose from compatible family pool",
    "minimumHunt": "Hard",
    "eventSource": "Dividend Week",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Rare Parts",
    "craftCost": 150,
    "craftTimeMin": 60,
    "craftTime": "1 hour",
    "dismantleParts": 30,
    "role": "HNW retention",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_uptime_cluster",
    "name": "Uptime Cluster",
    "rarity": "Rare",
    "category": "Operations",
    "families": "Data, Fintech, Exchange, Trading",
    "primaryPower": "+10% capacity",
    "secondaryPower": "-4 Operational Risk; +3% operating cost",
    "condition": "",
    "stackingGroup": "operations",
    "stageGate": "Growing",
    "guaranteedAcquisition": "Mastery III — choose from compatible family pool",
    "minimumHunt": "Hard",
    "eventSource": "Tech Rally",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Rare Parts",
    "craftCost": 150,
    "craftTimeMin": 60,
    "craftTime": "1 hour",
    "dismantleParts": 30,
    "role": "Infrastructure resilience",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_diversified_mandate",
    "name": "Diversified Mandate",
    "rarity": "Rare",
    "category": "Risk",
    "families": "Asset Management, Wealth",
    "primaryPower": "-6 Concentration Risk",
    "secondaryPower": "+5% activity efficiency",
    "condition": "Largest segment <=70%",
    "stackingGroup": "risk",
    "stageGate": "Growing",
    "guaranteedAcquisition": "Mastery III — choose from compatible family pool",
    "minimumHunt": "Hard",
    "eventSource": "Market Correction",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Rare Parts",
    "craftCost": 150,
    "craftTimeMin": 60,
    "craftTime": "1 hour",
    "dismantleParts": 30,
    "role": "Diversification",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_momentum_mandate",
    "name": "Momentum Mandate",
    "rarity": "Rare",
    "category": "Market",
    "families": "Asset Management, Trading",
    "primaryPower": "+10% activity efficiency",
    "secondaryPower": "+5 Market Risk",
    "condition": "Market State = Bull or Expansion",
    "stackingGroup": "market",
    "stageGate": "Growing",
    "guaranteedAcquisition": "Mastery III — choose from compatible family pool",
    "minimumHunt": "Hard",
    "eventSource": "Bull Market",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Rare Parts",
    "craftCost": 150,
    "craftTimeMin": 60,
    "craftTime": "1 hour",
    "dismantleParts": 30,
    "role": "Bull exposure",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_corporate_coverage_team",
    "name": "Corporate Coverage Team",
    "rarity": "Rare",
    "category": "Institutional",
    "families": "Investment Banking, Advisory, Banking",
    "primaryPower": "+10% Corporate Client acquisition",
    "secondaryPower": "+3 Reputation Risk if Service <70",
    "condition": "Service Quality >=70",
    "stackingGroup": "institutional",
    "stageGate": "Growing",
    "guaranteedAcquisition": "Mastery III — choose from compatible family pool",
    "minimumHunt": "Hard",
    "eventSource": "M&A Boom",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Rare Parts",
    "craftCost": 150,
    "craftTimeMin": 60,
    "craftTime": "1 hour",
    "dismantleParts": 30,
    "role": "Corporate coverage",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_risk_pooling",
    "name": "Risk Pooling",
    "rarity": "Rare",
    "category": "Risk",
    "families": "Insurance",
    "primaryPower": "+8% retention",
    "secondaryPower": "-4 Reputation Risk; -3% acquisition",
    "condition": "",
    "stackingGroup": "risk",
    "stageGate": "Growing",
    "guaranteedAcquisition": "Mastery III — choose from compatible family pool",
    "minimumHunt": "Hard",
    "eventSource": "Market Correction",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Rare Parts",
    "craftCost": 150,
    "craftTimeMin": 60,
    "craftTime": "1 hour",
    "dismantleParts": 30,
    "role": "Insurance stability",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_dynamic_pricing_engine",
    "name": "Dynamic Pricing Engine",
    "rarity": "Rare",
    "category": "Operations",
    "families": "Insurance, Lending, Brokerage",
    "primaryPower": "+8% activity efficiency",
    "secondaryPower": "+4 Reputation Risk if Service <70",
    "condition": "Service Quality >=70",
    "stackingGroup": "operations",
    "stageGate": "Growing",
    "guaranteedAcquisition": "Mastery III — choose from compatible family pool",
    "minimumHunt": "Hard",
    "eventSource": "Rate Hike",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Rare Parts",
    "craftCost": 150,
    "craftTimeMin": 60,
    "craftTime": "1 hour",
    "dismantleParts": 30,
    "role": "Pricing strategy",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_smart_liquidity_router",
    "name": "Smart Liquidity Router",
    "rarity": "Rare",
    "category": "Liquidity",
    "families": "Exchange, Market Making, FX, Treasury",
    "primaryPower": "+10% capacity",
    "secondaryPower": "-6 Liquidity Risk; +3 Market Risk",
    "condition": "",
    "stackingGroup": "liquidity",
    "stageGate": "Growing",
    "guaranteedAcquisition": "Mastery III — choose from compatible family pool",
    "minimumHunt": "Hard",
    "eventSource": "Liquidity Crunch",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Rare Parts",
    "craftCost": 150,
    "craftTimeMin": 60,
    "craftTime": "1 hour",
    "dismantleParts": 30,
    "role": "Liquidity infrastructure",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_research_signal_stack",
    "name": "Research Signal Stack",
    "rarity": "Rare",
    "category": "Research",
    "families": "Research, Data, Brokerage, Asset Management",
    "primaryPower": "+9% activity efficiency",
    "secondaryPower": "+4 Service Quality; +2 Operational Risk",
    "condition": "",
    "stackingGroup": "research",
    "stageGate": "Growing",
    "guaranteedAcquisition": "Mastery III — choose from compatible family pool",
    "minimumHunt": "Hard",
    "eventSource": "Tech Rally",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Rare Parts",
    "craftCost": 150,
    "craftTimeMin": 60,
    "craftTime": "1 hour",
    "dismantleParts": 30,
    "role": "Research alpha",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_credit_portfolio_guard",
    "name": "Credit Portfolio Guard",
    "rarity": "Rare",
    "category": "Credit",
    "families": "Lending, Banking",
    "primaryPower": "-8 Credit Risk",
    "secondaryPower": "-4 Concentration Risk; -5% activity efficiency",
    "condition": "",
    "stackingGroup": "credit",
    "stageGate": "Growing",
    "guaranteedAcquisition": "Mastery III — choose from compatible family pool",
    "minimumHunt": "Hard",
    "eventSource": "Credit Boom",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Rare Parts",
    "craftCost": 150,
    "craftTimeMin": 60,
    "craftTime": "1 hour",
    "dismantleParts": 30,
    "role": "Credit quality",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_client_churn_predictor",
    "name": "Client Churn Predictor",
    "rarity": "Rare",
    "category": "Service",
    "families": "Banking, Insurance, Wealth, Advisory",
    "primaryPower": "+9% retention",
    "secondaryPower": "+4 Service Quality; +2% operating cost",
    "condition": "",
    "stackingGroup": "service",
    "stageGate": "Growing",
    "guaranteedAcquisition": "Mastery III — choose from compatible family pool",
    "minimumHunt": "Hard",
    "eventSource": "Earnings Season",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Rare Parts",
    "craftCost": 150,
    "craftTimeMin": 60,
    "craftTime": "1 hour",
    "dismantleParts": 30,
    "role": "Retention analytics",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_institutional_execution_desk",
    "name": "Institutional Execution Desk",
    "rarity": "Rare",
    "category": "Institutional",
    "families": "Investment Banking, Exchange, Brokerage",
    "primaryPower": "+10% Corporate Client acquisition",
    "secondaryPower": "+7% activity efficiency; +3 Operational Risk",
    "condition": "",
    "stackingGroup": "institutional",
    "stageGate": "Growing",
    "guaranteedAcquisition": "Mastery III — choose from compatible family pool",
    "minimumHunt": "Hard",
    "eventSource": "IPO Week",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Rare Parts",
    "craftCost": 150,
    "craftTimeMin": 60,
    "craftTime": "1 hour",
    "dismantleParts": 30,
    "role": "Institutional throughput",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_treasury_duration_hedge",
    "name": "Treasury Duration Hedge",
    "rarity": "Rare",
    "category": "Liquidity",
    "families": "Treasury, Banking, Asset Management",
    "primaryPower": "-7 Liquidity Risk",
    "secondaryPower": "-5 Market Risk; -4% activity efficiency",
    "condition": "",
    "stackingGroup": "liquidity",
    "stageGate": "Growing",
    "guaranteedAcquisition": "Mastery III — choose from compatible family pool",
    "minimumHunt": "Hard",
    "eventSource": "Rate Hike",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Rare Parts",
    "craftCost": 150,
    "craftTimeMin": 60,
    "craftTime": "1 hour",
    "dismantleParts": 30,
    "role": "Rate defense",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_fraud_intelligence_network",
    "name": "Fraud Intelligence Network",
    "rarity": "Rare",
    "category": "Risk",
    "families": "Banking, Fintech, Insurance, Brokerage",
    "primaryPower": "-8 Operational Risk",
    "secondaryPower": "-4 Reputation Risk; -3% capacity",
    "condition": "",
    "stackingGroup": "risk",
    "stageGate": "Growing",
    "guaranteedAcquisition": "Mastery III — choose from compatible family pool",
    "minimumHunt": "Hard",
    "eventSource": "Regulatory Approval",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Rare Parts",
    "craftCost": 150,
    "craftTimeMin": 60,
    "craftTime": "1 hour",
    "dismantleParts": 30,
    "role": "Fraud defense",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_hnw_referral_network",
    "name": "HNW Referral Network",
    "rarity": "Rare",
    "category": "Wealth",
    "families": "Wealth, Private Banking, Advisory",
    "primaryPower": "+10% HNW acquisition",
    "secondaryPower": "+5% retention; -4% General Consumer acquisition",
    "condition": "",
    "stackingGroup": "wealth",
    "stageGate": "Growing",
    "guaranteedAcquisition": "Mastery III — choose from compatible family pool",
    "minimumHunt": "Hard",
    "eventSource": "Dividend Week",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Rare Parts",
    "craftCost": 150,
    "craftTimeMin": 60,
    "craftTime": "1 hour",
    "dismantleParts": 30,
    "role": "HNW network",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_operational_redundancy",
    "name": "Operational Redundancy",
    "rarity": "Rare",
    "category": "Operations",
    "families": "All",
    "primaryPower": "-7 Operational Risk",
    "secondaryPower": "+7% capacity; +4% operating cost",
    "condition": "",
    "stackingGroup": "operations",
    "stageGate": "Growing",
    "guaranteedAcquisition": "Mastery III — choose from compatible family pool",
    "minimumHunt": "Hard",
    "eventSource": "Volatility Spike",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Rare Parts",
    "craftCost": 150,
    "craftTimeMin": 60,
    "craftTime": "1 hour",
    "dismantleParts": 30,
    "role": "Resilience",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_deposit_sweep_engine",
    "name": "Deposit Sweep Engine",
    "rarity": "Epic",
    "category": "Liquidity",
    "families": "Banking, Treasury",
    "primaryPower": "+12% capacity",
    "secondaryPower": "If reserve <8%: +6 Liquidity Risk",
    "condition": "Reserve Ratio >=15%",
    "stackingGroup": "liquidity",
    "stageGate": "Established",
    "guaranteedAcquisition": "Mastery IV — choose from compatible family pool",
    "minimumHunt": "Elite",
    "eventSource": "Liquidity Crunch",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Epic Parts",
    "craftCost": 400,
    "craftTimeMin": 240,
    "craftTime": "4 hours",
    "dismantleParts": 80,
    "role": "Conditional treasury",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_volatility_engine",
    "name": "Volatility Engine",
    "rarity": "Epic",
    "category": "Market",
    "families": "Trading, Exchange, Market Making",
    "primaryPower": "+14% activity efficiency",
    "secondaryPower": "+8 Market Risk",
    "condition": "Market State = Bull/Expansion OR Volatility Spike active",
    "stackingGroup": "market",
    "stageGate": "Established",
    "guaranteedAcquisition": "Mastery IV — choose from compatible family pool",
    "minimumHunt": "Elite",
    "eventSource": "Volatility Spike",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Epic Parts",
    "craftCost": 400,
    "craftTimeMin": 240,
    "craftTime": "4 hours",
    "dismantleParts": 80,
    "role": "High volatility offense",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_family_office_protocol",
    "name": "Family Office Protocol",
    "rarity": "Epic",
    "category": "Wealth",
    "families": "Wealth, Private Banking",
    "primaryPower": "+12% HNW retention",
    "secondaryPower": "-5% capacity",
    "condition": "Reputation >=80",
    "stackingGroup": "wealth",
    "stageGate": "Established",
    "guaranteedAcquisition": "Mastery IV — choose from compatible family pool",
    "minimumHunt": "Elite",
    "eventSource": "Dividend Week",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Epic Parts",
    "craftCost": 400,
    "craftTimeMin": 240,
    "craftTime": "4 hours",
    "dismantleParts": 80,
    "role": "Prestige wealth",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_credit_scoring_engine",
    "name": "Credit Scoring Engine",
    "rarity": "Epic",
    "category": "Credit",
    "families": "Lending, Banking",
    "primaryPower": "+10% Small Business acquisition",
    "secondaryPower": "-5 Credit Risk",
    "condition": "Service Quality >=75",
    "stackingGroup": "credit",
    "stageGate": "Established",
    "guaranteedAcquisition": "Mastery IV — choose from compatible family pool",
    "minimumHunt": "Elite",
    "eventSource": "Credit Boom",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Epic Parts",
    "craftCost": 400,
    "craftTimeMin": 240,
    "craftTime": "4 hours",
    "dismantleParts": 80,
    "role": "Quality lending",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_deep_liquidity_engine",
    "name": "Deep Liquidity Engine",
    "rarity": "Epic",
    "category": "Liquidity",
    "families": "Market Making, Exchange",
    "primaryPower": "+12% capacity",
    "secondaryPower": "-6 Liquidity Risk; +4 Market Risk",
    "condition": "",
    "stackingGroup": "liquidity",
    "stageGate": "Established",
    "guaranteedAcquisition": "Mastery IV — choose from compatible family pool",
    "minimumHunt": "Elite",
    "eventSource": "Liquidity Crunch",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Epic Parts",
    "craftCost": 400,
    "craftTimeMin": 240,
    "craftTime": "4 hours",
    "dismantleParts": 80,
    "role": "Market infrastructure",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_deal_execution_room",
    "name": "Deal Execution Room",
    "rarity": "Epic",
    "category": "Institutional",
    "families": "Investment Banking",
    "primaryPower": "+12% activity efficiency",
    "secondaryPower": "+4 Operational Risk",
    "condition": "Corporate Client utilization >=50%",
    "stackingGroup": "institutional",
    "stageGate": "Established",
    "guaranteedAcquisition": "Mastery IV — choose from compatible family pool",
    "minimumHunt": "Elite",
    "eventSource": "M&A Boom",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Epic Parts",
    "craftCost": 400,
    "craftTimeMin": 240,
    "craftTime": "4 hours",
    "dismantleParts": 80,
    "role": "Deal throughput",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_adaptive_data_fabric",
    "name": "Adaptive Data Fabric",
    "rarity": "Epic",
    "category": "Research",
    "families": "Research, Data, Fintech",
    "primaryPower": "+8% activity efficiency",
    "secondaryPower": "+5 Service Quality",
    "condition": "Operational Risk <=50",
    "stackingGroup": "research",
    "stageGate": "Established",
    "guaranteedAcquisition": "Mastery IV — choose from compatible family pool",
    "minimumHunt": "Elite",
    "eventSource": "Tech Rally",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Epic Parts",
    "craftCost": 400,
    "craftTimeMin": 240,
    "craftTime": "4 hours",
    "dismantleParts": 80,
    "role": "Quality-conditioned tech",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_stress_test_framework",
    "name": "Stress-Test Framework",
    "rarity": "Epic",
    "category": "Risk",
    "families": "Banking, Treasury, Insurance, Asset Management",
    "primaryPower": "-10 combined relevant Risk points",
    "secondaryPower": "-6% activity efficiency",
    "condition": "Composite Risk >=35",
    "stackingGroup": "risk",
    "stageGate": "Established",
    "guaranteedAcquisition": "Mastery IV — choose from compatible family pool",
    "minimumHunt": "Elite",
    "eventSource": "Market Correction",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Epic Parts",
    "craftCost": 400,
    "craftTimeMin": 240,
    "craftTime": "4 hours",
    "dismantleParts": 80,
    "role": "Crisis defense",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_ipo_syndication_desk",
    "name": "IPO Syndication Desk",
    "rarity": "Epic",
    "category": "Institutional",
    "families": "Investment Banking, Brokerage, Exchange",
    "primaryPower": "+12% Corporate Client acquisition",
    "secondaryPower": "+8% activity efficiency; +4 Reputation Risk",
    "condition": "IPO Week active",
    "stackingGroup": "institutional",
    "stageGate": "Established",
    "guaranteedAcquisition": "Mastery IV — choose from compatible family pool",
    "minimumHunt": "Elite",
    "eventSource": "IPO Week",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Epic Parts",
    "craftCost": 400,
    "craftTimeMin": 240,
    "craftTime": "4 hours",
    "dismantleParts": 80,
    "role": "Event specialization",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_cross_market_arbitrage_engine",
    "name": "Cross-Market Arbitrage Engine",
    "rarity": "Epic",
    "category": "Market",
    "families": "Trading, Exchange, Market Making, FX",
    "primaryPower": "+13% activity efficiency",
    "secondaryPower": "+7 Market Risk; +3 Operational Risk",
    "condition": "Market State != Crisis",
    "stackingGroup": "market",
    "stageGate": "Established",
    "guaranteedAcquisition": "Mastery IV — choose from compatible family pool",
    "minimumHunt": "Elite",
    "eventSource": "Bull Market",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Epic Parts",
    "craftCost": 400,
    "craftTimeMin": 240,
    "craftTime": "4 hours",
    "dismantleParts": 80,
    "role": "Cross-market offense",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_advanced_claims_analytics",
    "name": "Advanced Claims Analytics",
    "rarity": "Epic",
    "category": "Service",
    "families": "Insurance",
    "primaryPower": "+10% retention",
    "secondaryPower": "+6 Service Quality; -5 Operational Risk",
    "condition": "Utilization <=95%",
    "stackingGroup": "service",
    "stageGate": "Established",
    "guaranteedAcquisition": "Mastery IV — choose from compatible family pool",
    "minimumHunt": "Elite",
    "eventSource": "Regulatory Approval",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Epic Parts",
    "craftCost": 400,
    "craftTimeMin": 240,
    "craftTime": "4 hours",
    "dismantleParts": 80,
    "role": "Insurance analytics",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_dynamic_capital_allocation",
    "name": "Dynamic Capital Allocation",
    "rarity": "Epic",
    "category": "Risk",
    "families": "Asset Management, Wealth, Treasury",
    "primaryPower": "-8 Concentration Risk",
    "secondaryPower": "+8% activity efficiency",
    "condition": "No segment >60%",
    "stackingGroup": "risk",
    "stageGate": "Established",
    "guaranteedAcquisition": "Mastery IV — choose from compatible family pool",
    "minimumHunt": "Elite",
    "eventSource": "Market Correction",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Epic Parts",
    "craftCost": 400,
    "craftTimeMin": 240,
    "craftTime": "4 hours",
    "dismantleParts": 80,
    "role": "Capital discipline",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_regulatory_intelligence_suite",
    "name": "Regulatory Intelligence Suite",
    "rarity": "Epic",
    "category": "Risk",
    "families": "Banking, Brokerage, Fintech, Insurance, Investment Banking",
    "primaryPower": "-8 Reputation Risk",
    "secondaryPower": "-5 Operational Risk; -4% activity efficiency",
    "condition": "",
    "stackingGroup": "risk",
    "stageGate": "Established",
    "guaranteedAcquisition": "Mastery IV — choose from compatible family pool",
    "minimumHunt": "Elite",
    "eventSource": "Regulatory Approval",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Epic Parts",
    "craftCost": 400,
    "craftTimeMin": 240,
    "craftTime": "4 hours",
    "dismantleParts": 80,
    "role": "Compliance defense",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_enterprise_risk_cockpit",
    "name": "Enterprise Risk Cockpit",
    "rarity": "Epic",
    "category": "Risk",
    "families": "All",
    "primaryPower": "-6 Operational Risk",
    "secondaryPower": "-5 highest applicable Market/Credit Risk; -4% activity efficiency",
    "condition": "Composite Risk >=30",
    "stackingGroup": "risk",
    "stageGate": "Established",
    "guaranteedAcquisition": "Mastery IV — choose from compatible family pool",
    "minimumHunt": "Elite",
    "eventSource": "Market Correction",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Epic Parts",
    "craftCost": 400,
    "craftTimeMin": 240,
    "craftTime": "4 hours",
    "dismantleParts": 80,
    "role": "Enterprise risk",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_strategic_client_network",
    "name": "Strategic Client Network",
    "rarity": "Epic",
    "category": "Institutional",
    "families": "Investment Banking, Private Banking, Wealth, Advisory",
    "primaryPower": "+12% Corporate/HNW acquisition",
    "secondaryPower": "+6% retention; -5% General Consumer acquisition",
    "condition": "Reputation >=80",
    "stackingGroup": "institutional",
    "stageGate": "Established",
    "guaranteedAcquisition": "Mastery IV — choose from compatible family pool",
    "minimumHunt": "Elite",
    "eventSource": "M&A Boom",
    "earnedPackSource": "Advanced / Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Epic Parts",
    "craftCost": 400,
    "craftTimeMin": 240,
    "craftTime": "4 hours",
    "dismantleParts": 80,
    "role": "Strategic relationships",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_fortress_balance_sheet",
    "name": "Fortress Balance Sheet",
    "rarity": "Legendary",
    "category": "Risk",
    "families": "Banking, Treasury, Private Banking",
    "primaryPower": "-12 Liquidity Risk",
    "secondaryPower": "-8 Credit Risk; -8% activity efficiency",
    "condition": "",
    "stackingGroup": "risk",
    "stageGate": "Elite",
    "guaranteedAcquisition": "Mastery V — choose from compatible family pool",
    "minimumHunt": "Jackpot",
    "eventSource": "Bank Run",
    "earnedPackSource": "Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Legendary Parts",
    "craftCost": 1000,
    "craftTimeMin": 720,
    "craftTime": "12 hours",
    "dismantleParts": 200,
    "role": "Transformative defense",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_trusted_institution_charter",
    "name": "Trusted Institution Charter",
    "rarity": "Legendary",
    "category": "Customer",
    "families": "Banking, Wealth, Private Banking, Investment Banking",
    "primaryPower": "+10% HNW/Corporate acquisition",
    "secondaryPower": "+8% retention",
    "condition": "Reputation >=85 AND Composite Risk <=40",
    "stackingGroup": "customer",
    "stageGate": "Elite",
    "guaranteedAcquisition": "Mastery V — choose from compatible family pool",
    "minimumHunt": "Jackpot",
    "eventSource": "Regulatory Approval",
    "earnedPackSource": "Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Legendary Parts",
    "craftCost": 1000,
    "craftTimeMin": 720,
    "craftTime": "12 hours",
    "dismantleParts": 200,
    "role": "Trust prestige",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_adaptive_market_desk",
    "name": "Adaptive Market Desk",
    "rarity": "Legendary",
    "category": "Market",
    "families": "Trading, Brokerage, Exchange, Market Making",
    "primaryPower": "Bull/Expansion: +12% activity efficiency",
    "secondaryPower": "Correction/Risk-Off: -8 Market Risk",
    "condition": "Market state branch",
    "stackingGroup": "market",
    "stageGate": "Elite",
    "guaranteedAcquisition": "Mastery V — choose from compatible family pool",
    "minimumHunt": "Jackpot",
    "eventSource": "Market Correction",
    "earnedPackSource": "Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Legendary Parts",
    "craftCost": 1000,
    "craftTimeMin": 720,
    "craftTime": "12 hours",
    "dismantleParts": 200,
    "role": "Cycle-adaptive",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_integrated_data_fabric",
    "name": "Integrated Data Fabric",
    "rarity": "Legendary",
    "category": "Operations",
    "families": "Data, Research, Fintech, Exchange",
    "primaryPower": "+10% capacity",
    "secondaryPower": "+6 Service Quality; -5 Operational Risk; +6% operating cost",
    "condition": "",
    "stackingGroup": "operations",
    "stageGate": "Elite",
    "guaranteedAcquisition": "Mastery V — choose from compatible family pool",
    "minimumHunt": "Jackpot",
    "eventSource": "Tech Rally",
    "earnedPackSource": "Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Legendary Parts",
    "craftCost": 1000,
    "craftTimeMin": 720,
    "craftTime": "12 hours",
    "dismantleParts": 200,
    "role": "Infrastructure prestige",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_sovereign_discipline",
    "name": "Sovereign Discipline",
    "rarity": "Legendary",
    "category": "Risk",
    "families": "Asset Management, Treasury",
    "primaryPower": "-10 Concentration Risk",
    "secondaryPower": "-8 Liquidity Risk; -6% activity efficiency",
    "condition": "",
    "stackingGroup": "risk",
    "stageGate": "Elite",
    "guaranteedAcquisition": "Mastery V — choose from compatible family pool",
    "minimumHunt": "Jackpot",
    "eventSource": "Rate Hike",
    "earnedPackSource": "Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Legendary Parts",
    "craftCost": 1000,
    "craftTimeMin": 720,
    "craftTime": "12 hours",
    "dismantleParts": 200,
    "role": "Capital preservation",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_diversified_services_charter",
    "name": "Diversified Services Charter",
    "rarity": "Legendary",
    "category": "Customer",
    "families": "Multi-Service",
    "primaryPower": "+8% retention",
    "secondaryPower": "-5 Concentration Risk; +6% acquisition",
    "condition": "3+ customer segments each >=10% and no segment >60%",
    "stackingGroup": "customer",
    "stageGate": "Elite",
    "guaranteedAcquisition": "Mastery V — choose from compatible family pool",
    "minimumHunt": "Jackpot",
    "eventSource": "Earnings Season",
    "earnedPackSource": "Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Legendary Parts",
    "craftCost": 1000,
    "craftTimeMin": 720,
    "craftTime": "12 hours",
    "dismantleParts": 200,
    "role": "Multi-service balance",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_global_liquidity_mesh",
    "name": "Global Liquidity Mesh",
    "rarity": "Legendary",
    "category": "Liquidity",
    "families": "Exchange, Market Making, Treasury, FX",
    "primaryPower": "+15% capacity",
    "secondaryPower": "-10 Liquidity Risk; +6 Market Risk",
    "condition": "Utilization >=50%",
    "stackingGroup": "liquidity",
    "stageGate": "Elite",
    "guaranteedAcquisition": "Mastery V — choose from compatible family pool",
    "minimumHunt": "Jackpot",
    "eventSource": "Liquidity Crunch",
    "earnedPackSource": "Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Legendary Parts",
    "craftCost": 1000,
    "craftTimeMin": 720,
    "craftTime": "12 hours",
    "dismantleParts": 200,
    "role": "Global liquidity",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_alpha_research_network",
    "name": "Alpha Research Network",
    "rarity": "Legendary",
    "category": "Research",
    "families": "Research, Data, Asset Management, Brokerage",
    "primaryPower": "+12% activity efficiency",
    "secondaryPower": "+6 Service Quality; +5 Operational Risk",
    "condition": "Operational Risk <=45",
    "stackingGroup": "research",
    "stageGate": "Elite",
    "guaranteedAcquisition": "Mastery V — choose from compatible family pool",
    "minimumHunt": "Jackpot",
    "eventSource": "Tech Rally",
    "earnedPackSource": "Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Legendary Parts",
    "craftCost": 1000,
    "craftTimeMin": 720,
    "craftTime": "12 hours",
    "dismantleParts": 200,
    "role": "Research prestige",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_institutional_trust_engine",
    "name": "Institutional Trust Engine",
    "rarity": "Legendary",
    "category": "Institutional",
    "families": "Investment Banking, Private Banking, Exchange",
    "primaryPower": "+12% Corporate/HNW acquisition",
    "secondaryPower": "-6 Reputation Risk; -5% capacity",
    "condition": "Reputation >=90",
    "stackingGroup": "institutional",
    "stageGate": "Elite",
    "guaranteedAcquisition": "Mastery V — choose from compatible family pool",
    "minimumHunt": "Jackpot",
    "eventSource": "M&A Boom",
    "earnedPackSource": "Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Legendary Parts",
    "craftCost": 1000,
    "craftTimeMin": 720,
    "craftTime": "12 hours",
    "dismantleParts": 200,
    "role": "Institutional trust",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  },
  {
    "id": "mod_resilient_market_infrastructure",
    "name": "Resilient Market Infrastructure",
    "rarity": "Legendary",
    "category": "Event",
    "families": "Exchange, Market Making, Data, Fintech",
    "primaryPower": "-20% eligible negative event magnitude",
    "secondaryPower": "+8% capacity outside Crisis",
    "condition": "Operational Risk <=50",
    "stackingGroup": "event",
    "stageGate": "Elite",
    "guaranteedAcquisition": "Mastery V — choose from compatible family pool",
    "minimumHunt": "Jackpot",
    "eventSource": "Volatility Spike",
    "earnedPackSource": "Prestige Earned Pack",
    "cashPackEligible": false,
    "craftParts": "Legendary Parts",
    "craftCost": 1000,
    "craftTimeMin": 720,
    "craftTime": "12 hours",
    "dismantleParts": 200,
    "role": "System resilience",
    "directPerformance": false,
    "directPlot": false,
    "notes": "Server-authoritative config; effects subject to stacking and hard caps."
  }
] as const;

export const MODULE_CATALOG_BY_ID: ReadonlyMap<string, CanonicalModuleCatalogEntry> = new Map(
  CANONICAL_MODULE_CATALOG.map((entry) => [entry.id, entry]),
);
