import type { MarketStage } from "./market_phase3.ts";
import { CASH_SCALE } from "./constants.ts";

export const PERFORMANCE_WEIGHTS = {
  economicActivity: 0.30,
  netBusinessRevenue: 0.20,
  activeCustomers: 0.15,
  customerGrowth: 0.10,
  utilization: 0.10,
  reputation: 0.05,
  riskManagement: 0.05,
  marketHunts: 0.05,
} as const;

export const PERFORMANCE_RULES = {
  weeklyPlotPool: 2_000_000,
  payoutExponent: 0.85,
  minimumScore: 35,
  minimumActiveDays: 3,
  minimumPlotAgeHours: 72,
  scoreCap: 120,
  capActivationPlayers: 500,
  maxPlayerPoolShare: 0.015,
  averageMultipleCap: 8,
} as const;

export type PerformanceTargetMode = "runtime" | "workbook";
export const DEFAULT_PERFORMANCE_TARGET_MODE: PerformanceTargetMode = "runtime";

export const PERFORMANCE_STAGE_RULES: Record<MarketStage, {
  activeCustomers: number;
  utilization: number;
  netRevenuePerDay: number;
  activityPerDay: number;
  newRetainedCustomers: number;
  huntTarget: number;
  reputationBaseline: number;
  riskBaseline: number;
  payoutWeight: number;
}> = {
  humble: { activeCustomers: 240.40196712, utilization: 0.5501189179, netRevenuePerDay: 2990.50415629, activityPerDay: 701.229184831, newRetainedCustomers: 36.060295068, huntTarget: 5, reputationBaseline: 55, riskBaseline: 10, payoutWeight: 1 },
  starter: { activeCustomers: 3341.358236, utilization: 0.4910873363, netRevenuePerDay: 50100.3876874, activityPerDay: 9623.13781711, newRetainedCustomers: 334.1358236, huntTarget: 8, reputationBaseline: 62, riskBaseline: 12, payoutWeight: 1.35 },
  growing: { activeCustomers: 26802.337416, utilization: 0.5574877263, netRevenuePerDay: 487748.116405, activityPerDay: 81245.7916708, newRetainedCustomers: 1608.14024496, huntTarget: 10, reputationBaseline: 70, riskBaseline: 14, payoutWeight: 1.8 },
  established: { activeCustomers: 158907.159931, utilization: 0.5804043287, netRevenuePerDay: 4071247.5768, activityPerDay: 548163.994579, newRetainedCustomers: 5561.750597585, huntTarget: 12, reputationBaseline: 78, riskBaseline: 16, payoutWeight: 2.5 },
  elite: { activeCustomers: 461056.17713, utilization: 0.8436171527, netRevenuePerDay: 14792354.6143, activityPerDay: 1806094.01882, newRetainedCustomers: 9221.1235426, huntTarget: 14, reputationBaseline: 86, riskBaseline: 18, payoutWeight: 3.4 },
  tycoon: { activeCustomers: 1243100.75837, utilization: 0.9441570366, netRevenuePerDay: 45738213.4503, activityPerDay: 4341887.63232, newRetainedCustomers: 12431.0075837, huntTarget: 16, reputationBaseline: 92, riskBaseline: 20, payoutWeight: 4.5 },
};

/**
 * v0.1 runtime targets generated by scripts/simulate_performance.ts from a
 * deterministic seven-day mixed-board run. Values are weekly totals except
 * activeCustomers, which is a weekly average. The workbook targets above are
 * intentionally retained as the long-term economy targets.
 */
export const PERFORMANCE_RUNTIME_TARGETS: Record<MarketStage, {
  activityPerWeek: number;
  revenuePerWeek: number;
  activeCustomers: number;
  newRetainedCustomers: number;
}> = {
  humble: { activityPerWeek: 2773.55, revenuePerWeek: 37.36, activeCustomers: 117.43, newRetainedCustomers: 53 },
  starter: { activityPerWeek: 11661.42, revenuePerWeek: 140.56, activeCustomers: 439.86, newRetainedCustomers: 326 },
  growing: { activityPerWeek: 28595.29, revenuePerWeek: 334.62, activeCustomers: 964, newRetainedCustomers: 149 },
  established: { activityPerWeek: 60590.15, revenuePerWeek: 734.17, activeCustomers: 2068.71, newRetainedCustomers: 1012 },
  elite: { activityPerWeek: 99731.67, revenuePerWeek: 1044.23, activeCustomers: 2734.71, newRetainedCustomers: 1424 },
  tycoon: { activityPerWeek: 164166.82, revenuePerWeek: 1645.86, activeCustomers: 4122, newRetainedCustomers: 1964 },
};

export type PerformanceMetrics = {
  stage: MarketStage;
  activityMinor: number;
  revenueMinor: number;
  averageActiveCustomers: number;
  newRetainedCustomers: number;
  averageUtilization: number;
  reputation: number;
  riskIndex: number;
  completedHunts: number;
  eventMissionPoints?: number;
  activeDays: number;
  plotAgeHours: number;
  finalized: boolean;
};

export type PerformanceScore = {
  components: {
    economicActivity: number;
    netBusinessRevenue: number;
    activeCustomers: number;
    customerGrowth: number;
    utilization: number;
    reputation: number;
    riskManagement: number;
    marketHunts: number;
  };
  weightedScore: number;
  eventMissionPoints: number;
  eligible: boolean;
  eligibilityReasons: string[];
};

function capped(value: number, cap: number): number {
  return Math.max(0, Math.min(cap, value));
}

function powerIndex(raw: number, target: number, exponent: number, cap: number): number {
  if (raw <= 0 || target <= 0) return 0;
  return capped(100 * Math.pow(raw / target, exponent), cap);
}

export function utilizationIndex(utilization: number): number {
  const value = Math.max(0, utilization);
  if (value <= 0.45) return capped((value / 0.45) * 75, 100);
  if (value <= 0.80) return 75 + ((value - 0.45) / 0.35) * 25;
  if (value <= 0.90) return 100;
  if (value <= 0.95) return 100 - ((value - 0.90) / 0.05) * 10;
  return capped(90 - ((Math.min(1, value) - 0.95) / 0.05) * 30, 100);
}

export function calculatePerformanceScore(metrics: PerformanceMetrics, targetMode: PerformanceTargetMode = DEFAULT_PERFORMANCE_TARGET_MODE): PerformanceScore {
  const baseline = PERFORMANCE_STAGE_RULES[metrics.stage];
  const targets = targetMode === "runtime" ? PERFORMANCE_RUNTIME_TARGETS[metrics.stage] : null;
  const components = {
    economicActivity: powerIndex(metrics.activityMinor / CASH_SCALE, targets?.activityPerWeek ?? baseline.activityPerDay * 7, 0.55, 130),
    netBusinessRevenue: powerIndex(metrics.revenueMinor / CASH_SCALE, targets?.revenuePerWeek ?? baseline.netRevenuePerDay * 7, 0.50, 125),
    activeCustomers: powerIndex(metrics.averageActiveCustomers, targets?.activeCustomers ?? baseline.activeCustomers, 0.50, 120),
    customerGrowth: powerIndex(metrics.newRetainedCustomers, targets?.newRetainedCustomers ?? baseline.newRetainedCustomers, 0.40, 120),
    utilization: utilizationIndex(metrics.averageUtilization),
    reputation: capped(metrics.reputation, 100),
    riskManagement: capped(100 - metrics.riskIndex, 100),
    marketHunts: capped(100 * Math.min(1, metrics.completedHunts / baseline.huntTarget), 100),
  };
  const weightedBase = Object.entries(components).reduce((sum, [key, value]) => {
    return sum + value * PERFORMANCE_WEIGHTS[key as keyof typeof PERFORMANCE_WEIGHTS];
  }, 0);
  const eventMissionPoints = Math.min(5, Math.max(0, metrics.eventMissionPoints ?? 0));
  const weightedScore = Math.min(120, weightedBase + eventMissionPoints);
  const eligibilityReasons: string[] = [];
  if (weightedScore < PERFORMANCE_RULES.minimumScore) eligibilityReasons.push(`Score must reach ${PERFORMANCE_RULES.minimumScore}.`);
  if (metrics.activeDays < PERFORMANCE_RULES.minimumActiveDays) eligibilityReasons.push(`Requires ${PERFORMANCE_RULES.minimumActiveDays} active days.`);
  if (metrics.plotAgeHours < PERFORMANCE_RULES.minimumPlotAgeHours) eligibilityReasons.push(`Plot must be ${PERFORMANCE_RULES.minimumPlotAgeHours} hours old.`);
  if (metrics.activityMinor <= 0) eligibilityReasons.push("Economic activity is required.");
  if (metrics.averageActiveCustomers <= 0) eligibilityReasons.push("Active customers are required.");
  if (!metrics.finalized) eligibilityReasons.push("The weekly snapshot is not finalized yet.");
  return { components, weightedScore: Number(weightedScore.toFixed(2)), eventMissionPoints, eligible: eligibilityReasons.length === 0, eligibilityReasons };
}

export function payoutWeight(score: number): number {
  return Math.pow(Math.max(0, score), PERFORMANCE_RULES.payoutExponent);
}

export type PayoutEntry = { id: string; stage: MarketStage; score: number };

export function allocateWeeklyPayouts(entries: PayoutEntry[], pool = PERFORMANCE_RULES.weeklyPlotPool): Map<string, number> {
  const payouts = new Map<string, number>();
  const eligible = entries.filter((entry) => entry.score > 0);
  if (!eligible.length) return payouts;
  const stageWeightTotal = eligible.reduce((sum, entry) => sum + PERFORMANCE_STAGE_RULES[entry.stage].payoutWeight, 0);
  for (const stage of Object.keys(PERFORMANCE_STAGE_RULES) as MarketStage[]) {
    const group = eligible.filter((entry) => entry.stage === stage);
    if (!group.length) continue;
    const groupWeight = group.reduce((sum, entry) => sum + PERFORMANCE_STAGE_RULES[entry.stage].payoutWeight, 0);
    const divisionPool = pool * groupWeight / stageWeightTotal;
    const weights = new Map(group.map((entry) => [entry.id, payoutWeight(entry.score)]));
    const totalWeight = [...weights.values()].reduce((sum, value) => sum + value, 0);
    const cap = group.length >= PERFORMANCE_RULES.capActivationPlayers
      ? Math.min(divisionPool * PERFORMANCE_RULES.maxPlayerPoolShare, divisionPool / group.length * PERFORMANCE_RULES.averageMultipleCap)
      : Number.POSITIVE_INFINITY;
    const remaining = new Set(group.map((entry) => entry.id));
    let remainingPool = divisionPool;
    while (remaining.size) {
      const remainingWeight = [...remaining].reduce((sum, id) => sum + (weights.get(id) ?? 0), 0);
      let cappedAny = false;
      for (const id of remaining) {
        const share = remainingPool * (weights.get(id) ?? 0) / Math.max(1e-9, remainingWeight);
        if (share > cap) {
          payouts.set(id, Math.floor(cap));
          remaining.delete(id);
          remainingPool -= cap;
          cappedAny = true;
        }
      }
      if (!cappedAny) {
        for (const id of remaining) payouts.set(id, Math.floor(remainingPool * (weights.get(id) ?? 0) / Math.max(1e-9, remainingWeight)));
        break;
      }
    }
  }
  return payouts;
}
